"""
tests/test_agent.py

Outcome-based security test suite for the `redeem_discount_code` tool.

Generated by inspecting app/agent.py and mapping every security boundary
to a concrete assertion. Tests are structured as:
  - Group 1: Happy Path
  - Group 2: Pydantic Input Validation (CONTEXT.md Rule 1)
  - Group 3: Rate Limiting (STRIDE: Denial of Service)
  - Group 4: Identity / Authorization (STRIDE: Spoofing, EoP)
  - Group 5: Code Existence Validation (STRIDE: Tampering)
  - Group 6: Single-Use Enforcement / Atomicity (STRIDE: Tampering)
  - Group 7: Input Normalization
  - Group 8: Error Message Sanitization (STRIDE: Information Disclosure)
  - Group 9: Concurrency / Race Condition (STRIDE: Tampering)
"""

import sys
import threading
import time

import pytest

# ---------------------------------------------------------------------------
# Module reload fixture — resets all mutable module-level state between tests:
#   _DISCOUNT_CODES (redeemed flags), _redemption_attempts (rate limiter),
#   _LOYALTY_ACCOUNTS, _AWARDED_ORDERS
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def reset_agent_state():
    """Reload app.agent before every test to reset shared in-memory state."""
    for key in list(sys.modules):
        if key.startswith("app"):
            del sys.modules[key]
    yield


def tool():
    """Return a freshly imported redeem_discount_code function."""
    from app.agent import redeem_discount_code

    return redeem_discount_code


# ===========================================================================
# Group 1 — Happy Path
# ===========================================================================


class TestHappyPath:
    def test_welcome50_redeemed_successfully(self):
        """WELCOME50 redeemed by a registered user returns success and discount."""
        result = tool()("user_001", "WELCOME50")
        assert "Success" in result
        assert "WELCOME50" in result
        assert "50% off" in result
        assert "user_001" in result

    def test_summer20_redeemed_successfully(self):
        """SUMMER20 redeemed by a registered user returns success and discount."""
        result = tool()("user_002", "SUMMER20")
        assert "Success" in result
        assert "SUMMER20" in result
        assert "20% off" in result

    def test_different_users_can_each_redeem_different_codes(self):
        """Two different users can each redeem their own codes."""
        r1 = tool()("user_001", "WELCOME50")
        r2 = tool()("user_002", "SUMMER20")
        assert "Success" in r1
        assert "Success" in r2


# ===========================================================================
# Group 2 — Pydantic Input Validation  (CONTEXT.md Rule 1)
# ===========================================================================


class TestPydanticInputValidation:
    def test_user_id_too_short_rejected(self):
        """user_id shorter than 3 chars fails Pydantic min_length."""
        result = tool()("ab", "WELCOME50")
        assert "Invalid input" in result
        assert "validation error" in result

    def test_user_id_too_long_rejected(self):
        """user_id longer than 50 chars fails Pydantic max_length."""
        long_id = "u" * 51
        result = tool()(long_id, "WELCOME50")
        assert "Invalid input" in result

    def test_user_id_with_special_chars_rejected(self):
        """user_id containing symbols outside ^[a-zA-Z0-9_-]$ fails pattern."""
        result = tool()("user@domain.com", "WELCOME50")
        assert "Invalid input" in result

    def test_user_id_with_sql_injection_rejected(self):
        """SQL injection in user_id is rejected by Pydantic pattern."""
        result = tool()("'; DROP TABLE users;--", "WELCOME50")
        assert "Invalid input" in result

    def test_user_id_with_newline_rejected(self):
        """Newline character in user_id is rejected by Pydantic pattern."""
        result = tool()("user\n001", "WELCOME50")
        assert "Invalid input" in result

    def test_code_too_short_rejected(self):
        """Code shorter than 4 chars fails Pydantic min_length."""
        result = tool()("user_001", "HI")
        assert "Invalid input" in result

    def test_code_too_long_rejected(self):
        """Code longer than 20 chars fails Pydantic max_length."""
        result = tool()("user_001", "A" * 21)
        assert "Invalid input" in result

    def test_code_with_special_chars_rejected(self):
        """Code containing symbols outside ^[A-Za-z0-9]$ fails pattern."""
        result = tool()("user_001", "WELCOME-50!")
        assert "Invalid input" in result

    def test_empty_code_rejected(self):
        """Empty string for code fails Pydantic min_length."""
        result = tool()("user_001", "")
        assert "Invalid input" in result

    def test_empty_user_id_rejected(self):
        """Empty string for user_id fails Pydantic min_length."""
        result = tool()("", "WELCOME50")
        assert "Invalid input" in result


# ===========================================================================
# Group 3 — Rate Limiting  (STRIDE: Denial of Service)
# ===========================================================================


class TestRateLimiting:
    def test_exceeding_rate_limit_returns_throttle_message(self):
        """After RATE_LIMIT_MAX_ATTEMPTS (5) calls, the user is rate-limited."""
        from app.agent import RATE_LIMIT_MAX_ATTEMPTS, RATE_LIMIT_WINDOW_SECONDS

        redeem = tool()
        # Exhaust the rate limit allowance (each call counts even if rejected)
        for _ in range(RATE_LIMIT_MAX_ATTEMPTS):
            redeem("user_001", "WELCOME50")

        # The next call should be throttled
        result = redeem("user_001", "SUMMER20")
        assert "Too many" in result
        assert str(RATE_LIMIT_WINDOW_SECONDS) in result

    def test_rate_limit_is_per_user_not_global(self):
        """Rate limit on user_001 does not affect user_002."""
        from app.agent import RATE_LIMIT_MAX_ATTEMPTS

        redeem = tool()
        # Exhaust user_001's rate limit
        for _ in range(RATE_LIMIT_MAX_ATTEMPTS):
            redeem("user_001", "WELCOME50")

        # user_002 should still succeed (different bucket)
        result = redeem("user_002", "SUMMER20")
        assert "Success" in result

    def test_expired_attempts_are_evicted_from_window(self):
        """Attempts older than the rate-limit window are not counted."""
        from app import agent as agent_module

        # Manually inject old timestamps (outside the window)
        old_time = time.monotonic() - agent_module.RATE_LIMIT_WINDOW_SECONDS - 1
        agent_module._redemption_attempts["user_001"] = [
            old_time
        ] * agent_module.RATE_LIMIT_MAX_ATTEMPTS

        # All old attempts should be evicted — this call should succeed
        result = tool()("user_001", "WELCOME50")
        assert "Success" in result


# ===========================================================================
# Group 4 — Identity / Authorization  (STRIDE: Spoofing, EoP)
# ===========================================================================


class TestIdentityAndAuthorization:
    def test_unregistered_user_cannot_redeem(self):
        """Users not in _REGISTERED_USERS are rejected before touching codes."""
        result = tool()("attacker_x", "WELCOME50")
        assert "not a registered customer" in result

    def test_unregistered_user_does_not_consume_code(self):
        """A failed redemption by an unregistered user leaves the code intact."""
        redeem = tool()
        redeem("attacker_x", "WELCOME50")  # rejected

        # Legitimate user should still be able to redeem
        result = redeem("user_001", "WELCOME50")
        assert "Success" in result

    def test_registered_users_are_accepted(self):
        """Each known registered user can successfully redeem a code."""
        from app.agent import _REGISTERED_USERS

        redeem = tool()
        codes = ["WELCOME50", "SUMMER20"]
        registered = list(_REGISTERED_USERS)[:2]
        for user, code in zip(registered, codes, strict=True):
            result = redeem(user, code)
            assert "Success" in result, f"Expected success for {user}"


# ===========================================================================
# Group 5 — Code Existence Validation  (STRIDE: Tampering)
# ===========================================================================


class TestCodeExistenceValidation:
    def test_unknown_code_is_rejected(self):
        """A code not in _DISCOUNT_CODES returns a 'not valid' message."""
        result = tool()("user_001", "FAKEOFF99")
        assert "not a valid discount code" in result

    def test_unknown_code_does_not_mark_anything_redeemed(self):
        """Attempting an unknown code does not corrupt the code store."""
        from app import agent as agent_module

        tool()("user_001", "INVALID99")
        # Real codes must remain unredeemed
        assert agent_module._DISCOUNT_CODES["WELCOME50"]["redeemed"] is False
        assert agent_module._DISCOUNT_CODES["SUMMER20"]["redeemed"] is False

    def test_partially_matching_code_is_rejected(self):
        """A code that is a substring of a valid code is rejected (exact match required)."""
        result = tool()(
            "user_001", "WELCOME"
        )  # too short — also fails Pydantic? No, 7 chars ok
        # WELCOME is not in _DISCOUNT_CODES — should be "not valid"
        assert "not a valid" in result or "Invalid input" in result


# ===========================================================================
# Group 6 — Single-Use Enforcement / Atomicity  (STRIDE: Tampering)
# ===========================================================================


class TestSingleUseEnforcement:
    def test_code_cannot_be_redeemed_twice_by_same_user(self):
        """A code that has already been redeemed is rejected on second attempt."""
        redeem = tool()
        first = redeem("user_001", "WELCOME50")
        second = redeem("user_001", "WELCOME50")
        assert "Success" in first
        assert "already been redeemed" in second

    def test_code_cannot_be_redeemed_by_different_user_after_first_use(self):
        """Once a code is redeemed by user_001, user_002 cannot use the same code."""
        redeem = tool()
        redeem("user_001", "WELCOME50")
        result = redeem("user_002", "WELCOME50")
        assert "already been redeemed" in result

    def test_redeemed_flag_is_persisted_in_store(self):
        """After redemption, the in-memory store reflects redeemed=True."""
        from app import agent as agent_module

        tool()("user_001", "WELCOME50")
        assert agent_module._DISCOUNT_CODES["WELCOME50"]["redeemed"] is True

    def test_second_code_is_independent_of_first(self):
        """Redeeming WELCOME50 does not affect SUMMER20's redeemed state."""
        from app import agent as agent_module

        tool()("user_001", "WELCOME50")
        assert agent_module._DISCOUNT_CODES["SUMMER20"]["redeemed"] is False


# ===========================================================================
# Group 7 — Input Normalization
# ===========================================================================


class TestInputNormalization:
    def test_lowercase_code_is_accepted(self):
        """Lowercase codes are normalized to uppercase before lookup."""
        result = tool()("user_001", "welcome50")
        assert "Success" in result
        assert "WELCOME50" in result

    def test_mixed_case_code_is_accepted(self):
        """Mixed-case codes are normalized correctly."""
        result = tool()("user_001", "Welcome50")
        assert "Success" in result

    def test_code_with_leading_trailing_whitespace_is_stripped(self):
        """Whitespace around the code is stripped before validation.

        Note: Pydantic pattern ^[A-Za-z0-9]+$ will reject spaces,
        so this tests that whitespace causes a validation error (not a crash).
        """
        result = tool()("user_001", "  WELCOME50  ")
        # Spaces fail the Pydantic pattern — expected: Invalid input
        assert "Invalid input" in result or "not a valid" in result


# ===========================================================================
# Group 8 — Error Message Sanitization  (STRIDE: Information Disclosure)
# ===========================================================================


class TestErrorMessageSanitization:
    def test_unregistered_user_error_does_not_echo_user_id(self):
        """Error for unregistered user should NOT echo the supplied user_id back."""
        malicious_id = "INJECTED_ID_xyz123"
        result = tool()(malicious_id, "WELCOME50")
        # The response should reject on Pydantic (special chars) or user check
        # Either way, the raw malicious_id should not appear verbatim
        assert malicious_id not in result

    def test_invalid_code_error_does_not_echo_code(self):
        """Error for invalid code should NOT echo the raw code string back."""
        result = tool()("user_001", "FAKECODE")
        assert "FAKECODE" not in result

    def test_pydantic_error_does_not_expose_raw_input(self):
        """Pydantic validation error message is generic — does not leak raw values."""
        result = tool()("user_001", "BAD CODE!")
        assert "BAD CODE!" not in result


# ===========================================================================
# Group 9 — Concurrency / Race Condition  (STRIDE: Tampering)
# ===========================================================================


class TestConcurrency:
    def test_concurrent_redemptions_only_one_succeeds(self):
        """Under concurrent load, WELCOME50 can only be redeemed once."""
        from app import agent as agent_module

        # Register a unique user ID for each thread to avoid per-user rate limiting (max 5)
        registered_users = [f"user_concurrent_{i:03d}" for i in range(10)]
        for user_id in registered_users:
            agent_module._REGISTERED_USERS.add(user_id)

        redeem = tool()
        results = []
        lock = threading.Lock()

        def attempt(user_id):
            result = redeem(user_id, "WELCOME50")
            with lock:
                results.append(result)

        threads = [
            threading.Thread(target=attempt, args=(user_id,))
            for user_id in registered_users
        ]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        success_count = sum(1 for r in results if "Success" in r)
        already_redeemed_count = sum(1 for r in results if "already been redeemed" in r)

        assert success_count == 1, f"Expected exactly 1 success, got {success_count}"
        assert already_redeemed_count == 9, (
            f"Expected 9 rejections, got {already_redeemed_count}"
        )
